
// for(integer i=1 ; i<=10 ;i++  ){
    
//     for(integer j=1;j<=10;j++){
        
//       System.debug(i +' x ' + j + '=' +  i*j);  
//     }
    
// }


// for(integer a=100; a>=0;a-=5){
//     System.debug('ticket left ' + a );
// }

Integer b=10;
for(b=1;b<=100;b+=2){
    b+=5;
    System.debug('After adding 5 ' + ' = ' + b);
    b*=2;
    System.debug('After multiplying by 2 ' +  ' = ' + b);
}


