// Declare 3 Integer variavles and initialize their values. 
// Write a code to print out the largest number by comparing them with each other. 

Integer num1=4;
Integer num2=5;
Integer num3=20;

if( num1>num2&&num2>num3){
    System.debug('The num1 is the largest'); 
} if (num1<num2&&num2>num3){
    System.debug('The num2 is the largest'); 
} if (num1<num2&&num2<num3){
    System.debug('The num3 is the largest'); 
}