// Declare and initialize an Integer variable. 
// checks if a given integer is positive, negative, or zero. 
// If the number is positive, the program should print "Positive." 
// If the number is negative, the program should print “negative”
// Else print Zero

integer num1=-5;
if( num1>0 ){
    system.debug('Positive');
    
}else if( num1<0 ){
     system.debug('Negative');
}else{
     system.debug('Zero');
}