// A Bonus Task 
// Given  2 Integer values : 
// Integer num1 = 10 ; 
// Integer num2 = 20 ;

// Swap the value of num1 , num2 
// so num1 become 20 and num2 become 10.
   
Integer num1 = 10;
Integer num2 = 20;

// Swap the values of num1 and num2
Integer temp = num1;
num1 = num2;
num2 = temp;

System.debug('num1: ' + num1); // Output: num1: 20
System.debug('num2: ' + num2); // Output: num2: 10




