@isTest
private class AccountControllerTest {
    

    @isTest(SeeAllData=true)
    static void testDifferentUserAccessRecord(){
        
        // Create a User with standard user profile
        // unique username
        String uniqueUserName = 'YourNameHere' + Datetime.now().getTime() + '@05hakan.com' ;
        // profile Id
        Profile p = [SELECT Name, Id
        FROM PROFILE
        WHERE Name = 'Standard User'
        LIMIT 1 ];
        // all the User Object details that required(will copy from the example)
        User u = new User(
            Alias = 'js',
            Email = 'standarduser@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = uniqueUserName
          );
        
        // Print out currently logged in username
        System.debug('Userinfo value is : ' + Userinfo.getName());
        
        List<Account> allAccounts1=AccountController.getAllAccounts();
        System.debug('allAccount1 value is : ' + allAccounts1.size());
        



        // run as newly created user and print out username
        System.runAs(u){

            System.debug('UserInfo.getName()  value is : ' + UserInfo.getName() );
            List<Account> allAccounts2=AccountController.getAllAccounts();
            System.debug('allAccount2 value is : ' + allAccounts2.size());

            //Assert
            
            
        }


        //run as this user
        //print out the detail of current user
    }

    @isTest
    static void testRunAsOtherRole(){
      
      // Creata a user (need profile Id and Role Id) with standard user profile and Eastern Sales Team Role
          // Create a user with standard user profile
      // unique username
      String uniqueUserName ='YourNameHere' +DateTime.now().getTime() +'@force.com';
      // profile Id
      Profile p = [ SELECT Name, Id FROM PROFILE WHERE Name = 'Standard User' LIMIT 1];
      // role Id 
      UserRole ur = [SELECT Name, Id FROM UserRole WHERE Name = 'Eastern Sales Team' LIMIT 1]; 
  
      // all the User Object details that required (will copy from the example)
      User u = new User(
        Alias = 'js',
        Email = 'standarduser@testorg.com',
        EmailEncodingKey = 'UTF-8',
        LastName = 'Testing',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US',
        ProfileId = p.Id,
        UserRoleId = ur.Id,
        TimeZoneSidKey = 'America/Los_Angeles',
        UserName = uniqueUserName
      );
  
  
  
    }

}